language: elixir
elixir:
  - 1.7
  - 1.6
  - 1.4
otp_release:
  - 21.2
  - 19.3
  - 18.3
matrix:
  - elixir: 1.4
    otp_release: 18.3
  - elixir: 1.5
    otp_release: 19.3
script:
  - mix test && mix credo
